### ISSUE TITLE
terminfo 'cr' null value exception

### ISSUE THREAD

**Issue by rich-murphey** [omniosorg/pkg5#4]
When TERM=256+color, I've seen exceptions in pkg.
When TERM=dumb, there was no exception.
Logged into the console of omnioscce, I see:

> pfexec env TERM='xterm+256color' pkg refresh
Traceback (most recent call last):
  File "/usr/bin/pkg", line 5452, in handle_errors
    __ret = func(*args, **kwargs)
  File "/usr/bin/pkg", line 5354, in main_func
    return func(api_inst, pargs)
  File "/usr/bin/pkg", line 3449, in publisher_refresh
    return __refresh(api_inst, pargs, full_refresh=full_refresh)
  File "/usr/bin/pkg", line 3413, in __refresh
    immediate=True, pubs=pubs)
  File "/usr/lib/python2.7/vendor-packages/pkg/client/api.py", line 2987, in refresh
    pubs=pubs, immediate=immediate)
  File "/usr/lib/python2.7/vendor-packages/pkg/client/api.py", line 3011, in __refresh
    progtrack=self.__progresstracker)
  File "/usr/lib/python2.7/vendor-packages/pkg/client/image.py", line 3318, in refresh_publishers
    progtrack.refresh_start_pub(pub)
  File "/usr/lib/python2.7/vendor-packages/pkg/client/progress.py", line 1220, in refresh_start_pub
    self._refresh_output_progress(outspec)
  File "/usr/lib/python2.7/vendor-packages/pkg/client/progress.py", line 2850, in _refresh_output_progress
    self._pe.cprint(msg, end="", erase=True)
  File "/usr/lib/python2.7/vendor-packages/pkg/client/printengine.py", line 155, in cprint
    self.erase()
  File "/usr/lib/python2.7/vendor-packages/pkg/client/printengine.py", line 139, in erase
    self.putp(self.__cr)
  File "/usr/lib/python2.7/vendor-packages/pkg/client/printengine.py", line 119, in putp
    self._out_file.write(self.__putp_re.sub("", string))
TypeError: expected string or buffer

at printengine.py" line 139, in the call to self.putp(self.__cr)
self.__cr is None even though cr should be defined as \r in xterm+256color.

I set a breakpoing on POSIXPrintEngine.__init__, and after:
self.__cr = curses.tigetstr("cr")
the value of self._POSIXPrintEngine__cr  was None.

So, somehow, it is getting a null value for 'cr' from terminfo.

Setting TERM to dumb is a workaround:
> pfexec env TERM='dumb' pkg refresh
Refreshing catalog 'omnios' ... Done

**Comment by rich-murphey** [comment]
Here's infocmp output for two to differing TERM values.
It does look like 'cr' is missing in xterm+256color.

>env TERM=dumb infocmp -C -r
Reconstructed via infocmp from file: /usr/share/lib/terminfo/d/dumb
dumb|80-column dumb tty:\
    :am:\
   :co#80:\
        :bl=^G:cr=\r:do=\n:sf=\n:bc@:


>env TERM=xterm+256color infocmp -C -r
Reconstructed via infocmp from file: /usr/share/lib/terminfo/x/xterm+256color
xterm+256color|xterm 256-color feature:\
   :cc:nc:ns:\
     :Co#256:pa#32767:\
      :.AB=!!! MUST CHANGE BY HAND !!!\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m:\
      :.AF=!!! MUST CHANGE BY HAND !!!\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m:\
       :.Ic=!!! MUST CHANGE BY HAND !!!\E]4;%p1%d;rgb\072%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\:\
   :bc@:nl@:

**Comment by hadfl** [comment]
from terminfo:
https://github.com/omniosorg/illumos-omnios/blob/master/usr/src/data/terminfo/terminfo.src#L175

you might consider using `TERM=xterm-256color` instead

**Comment by rich-murphey** [comment]
Yes, that look like the best solution.
I'm closing this since it's solved.
